### ISSUE TITLE
PoT Logging ideas - General Community Server perspective

### ISSUE THREAD

**Issue by menix1337** [Alderon-Games/pot-community-servers#1]
All these logs will be sorted with a certain "word" - differenciating them, so its easier to sort with bots and stuff.
(this is the PoTxxLog: part - obviously this PoT could be changed into AlderonChatLog.. etc)

This is a basic log overview of what most community servers would love to see as logs in the game. Reason some of it is so specified is because less is more - we all love logs, and a lot of servers will end up having set rules, and the logs below will make it easier for admins to follow them.

Down below is just examples - What we would love of you guys to think is that whenever you add something ingame; think if its applicable to a logging event. 

We would like to restrain away from Verbose logging of course, since the files will already become "quite big" with the logs.

We as hosters, would always love to see most as possible - this means for most of the events we would like to see Player Names, Alderon IDs & some Dinosaur information & Obviously Time Stamps. 

---

### Chat: 
 _PoTChatLog: [GLOBAL/GROUP-GROUPNUMBER/LOCAL] NAME [ALDERON-ID]: Message_

**Examples:**
PoTChatLog: [GLOBAL] MENIX [055-760-405]: Hello there!
PoTChatLog: [GROUP-291] MENIX [055-760-405]: Hello there!

---

### Kills / Deaths:
_PoTKillLog: PlayerA [ALDERON-ID] Dinosaur: DinoNameA Male Growth: GrowthNumberA killed PlayerB [ALDERON-ID] Dinosaur: DinoNameB Female Growth GrowthNumberB_

_PoTDeathLog: PlayerA [ALDERON-ID] Cause of death_

**Examples:**
PoTKillLog: MENIX [055-760-405] Dinosaur: Allosaurus Male Growth: 1.0 killed Examplesaurus [000-000-000] Dinosaur: Alioramus Male Growth 0.5

PoTDeathLog: MENIX [055-760-405] Dinosaur: Allosaurus Male Growth: 1.0 died by falling off a cliff / drowned / got nuked

---

### Player Joins/Leaves:
**If user already had a dinosaur**
PoTJoinLog: MENIX [055-760-405] has joined the server - Found existing Character - Dinosaur: Allosaurus Female Growth: 1.0 

**If user fresh spawn (New Character)**
PoTJoinLog: MENIX [055-760-405] has joined the server - Creating new Character - Dinosaur: Allosaurus Female Growth: 0.1 

**Leave**
PoTJoinLog: MENIX [055-760-405] has left the server - Dinosaur: Allosaurus Female Growth: 0.45

- Maybe something if a player swaps his character? (Then log the old & new dinosaur information)

---

### Admin Commands (Examples - this is something where you guys just think; Its a command, lets log it. Down below is just some examples to make the brains start thinking):
PoTAdminCmdLog: MENIX [055-760-405] entered specmode 
PoTAdminCmdLog: MENIX [055-760-405] left specmode

PoTAdminCmdLog: MENIX [055-760-405] Turned on Admin Names - while being in specmode
PoTAdminCmdLog: MENIX [055-760-405] Turned off Admin Names - while being in specmode

PoTAdminCmdLog: MENIX [055-760-405] Turned on Admin Names - without being in specmode
PoTAdminCmdLog: MENIX [055-760-405] Turned off Admin Names - without being in specmode

PoTAdminCmdLog: MENIX [055-760-405] Used Grow on Examplesaurus [000-000-000] Dinosaur: Albertaceratops Male GrowthBefore: 0.1 GrowthNow: 1.0

PoTAdminCmdLog: MENIX [055-760-405] Used Slay on Examplesaurus [000-000-000] Dinosaur: Albertaceratops Male Growth: 1.0

PoTAdminCmdLog: MENIX [055-760-405] Teleported Examplesaurus [000-000-000] Dinosaur: Albertaceratops Male Growth: 1.0 to him

PoTAdminCmdLog: MENIX [055-760-405] Teleported To Examplesaurus [000-000-000] Dinosaur: Albertaceratops Male Growth: 1.0

... And so on - this is just a list to start the brains with examples - Since we just got admin of course, I'm unsure of what commands there specificly is..

---

### User Commands

PoTUserCmdLog: MENIX [055-760-405] used unstuck
PoTUserCmdLog: MENIX [055-760-405] used XXXXX (Just general commands)

---

### Ingame events

PoTGameLog: MENIX [055-760-405] Dinosaur: Ceratosaurus Female Growth: 1.0 - Completed Quest Name: Kill Camptosaurus
... And what else ther now is to log

---

### Other Log Examples

**Group Joins/Leaves**
PoTGroupLog: MENIX [055-760-405] Dinosaur: Ceratosaurus Male Growth: 1.0 - Joined Group: Group-1245 Group Members: MENIX [055-760-405], ExamplesaurusA [000-000-000], ExamplesaurusB [000-000-000], ExamplesaurusC [000-000-000] (and maybe their dinosaur informations too)

PoTGroupLog: MENIX [055-760-405] Dinosaur: Ceratosaurus Female Growth: 1.0 - Left Group: Group-1245 Group Members: ExamplesaurusA [000-000-000], ExamplesaurusB [000-000-000], ExamplesaurusC [000-000-000] (and maybe their dinosaur informations too)

**Damage Events**
PoTDamageLog: MENIX [055-760-405] Dinosaur: Ceratosaurus Female  Growth: 1.0 attacked Examplesaurus [000-000-000] Dinosaur: Eotriceratops Male Growth: 0.45 for 2% of their health - remaining health: 98% 
- Reason that we have percentage here is because A: Maybe you guys wanna keep the specific values secret. B: No one knows how much 2309825 Damage is on something

**Comment by Paleocolour** [comment]
@menix1337 can you go through this one and confirm these are all implemented?
