### ISSUE TITLE
Server Configurations no longer working

### ISSUE THREAD

**Issue by k4moso** [Alderon-Games/pot-community-servers#102]
Hello,

The lines in our Game.ini settings seem to have abruptly stopped being read and working properly. We haven't changed them at all. For example CombatDeathPenaltyPercent no longer works, it's just the same growth loss percent as the default and we have reports from our Megalania players who we adjusted the stats to be immune to venom are no longer immune. So we have reason to believe that the rest of our adjusted dinosaur stats are not working either.

Again, we changed nothing at all in the .ini! These server aspects just stopped working after a routine restart one day, we are not sure when, but recently.

**Comment by k4moso** [comment]
This is still not working.

**Comment by AlderonEmu** [comment]
Please check that this bug is still occurring for you in the current patch!
