### ISSUE TITLE
Issues with character data loading

### ISSUE THREAD

**Issue by ILICKZI** [Alderon-Games/pot-community-servers#104]
This only happens with some ppl and if they log mobile and delete some characters they can load in but some cannot load in without being able to access early access to mobile so how can we fix this issue.  It brings me into the game just won't load character menu.  It allows me to receive invites and all. The active mods are acro, carchardontosaurus zhuch, noviana, ophis, asylum skins, suspect, deino, argent, carnotaurus, dilo, giga, theri, utah, yunna, rainbow skins, teutonia, and velo. Note all of these were werkimg fine till randomly only certain ppl could reload in while others randomly experienced this on PlayStation and could not get in and nobody had done anything different.  Some ppl who couldn't get in tried mobile and deleted characters and it let them in while others who don't have early access on mobile cannot get into the game to do this. How can we fix this guy's.  I know it's new to y'all as well.  I look forward to y'all's help and thank you all for everything that you all do..  by the way we own this server but it's also other ppl saying there having same issue with modded servers. Not just our server.

**Comment by AlderonEmu** [comment]
Please check that this bug is still occurring for you in the current patch!
