### ISSUE TITLE
Using /demote with no arguments crashes the server

### ISSUE THREAD

**Issue by CptFacepalm** [Alderon-Games/pot-community-servers#105]
**Description**: If an admin uses /demote without specifying a player to demote, the server will immediately crash

**How To Reproduce the Bug**: 
- Use `/demote` with no added arguments

**Video/Screenshot**: https://vimeo.com/779690108

**Game Version**: 0.0.0.23073-Shipping
**Alderon Games Username**: CptFacepalm
**Alderon Games ID**: 853-484-164

**Comment by Absurdponcho** [comment]
Fixed as of latest build
