### ISSUE TITLE
Teleport unsafe argument not working for rcon

### ISSUE THREAD

**Issue by daanhansen** [Alderon-Games/pot-community-servers#106]
## Expected Behavior
When using unsafe as an option in the teleport command via rcon, the command should work as intended and spawn player at coordinates, not on the ground level.

## Current Behavior
When specifying the safe/unsafe parameter, unsafe will not work and command wont execute at all.

## Reproduction Steps

- Log into server using rcon

- Try using the "teleport player coordinates unsafe" command

- Command wont work. Unable to teleport people in unsafe manner.

## Evidence
N/A

## Crash Logs

(If Applicable. No logs needed if there is no crash.)

## Build Information

**Game Version:** 0.0.0.2373

**Operating System & Version:**
Windows 10 Home

**Alderon Games ID:** 154-325-261

**Comment by Absurdponcho** [comment]
added fix in 23670
