### ISSUE TITLE
listwaters Command not showing every source and showing one called "None"on Gondwa

### ISSUE THREAD

**Issue by daanhansen** [Alderon-Games/pot-community-servers#107]
## Expected Behavior
We want a list of every single watersource, even rivers not connected to any lake or pond.

## Current Behavior
The command will return the following response:
SickleclawLake, None, BigQuillLake, WhistlingColumnsLake, GreenValley, UpperGrasslandLake, WhiteCliffsLake, YoungGroveLake, WorldsEdgeLake, CraterPond, TryantsLake, RedIsland, Hotspring22, Hotspring23, Hotspring5, Hotspring6, Hotspring10, Hotspring19, Hotspring18, Hotspring20, Hotspring9, Hotspring16, Hotspring12, Hotspring13, Hotspring21, Hotspring17, Hotspring15, Hotspring14, Hotspring11, Hotspring8, Hotspring7, Hotspring3, Hotspring2, Hotspring1, Hotspring4, Hotspring24, PutridLake, AcridLake,

As you can see there is a "None" and some rivers are not present in the list.
"TyrantsLake" is spelled wrong as "TryantsLake"

## Reproduction Steps

- Use the listwaters command on Gondwa

## Evidence (Screenshots & Videos)
One of the missing water sources.
![image](https://user-images.githubusercontent.com/34507172/209815311-b1724764-7fa8-4fb1-8bbc-dd9a28ac0f87.png)

## Build Information

**Game Version:** 0.0.0.23073

**Operating System & Version:**
Windows 10 home 64 bit

**Alderon Games ID:** 154-325-261

**Comment by AlderonEmu** [comment]
This has been forwarded for review, thank you!

**Comment by AlderonEmu** [comment]
This is fixed in a future patch!
