### ISSUE TITLE
Transferring leadership & creating groups causes game freeze & crash for individual users on server.

### ISSUE THREAD

**Issue by Lurulai** [Alderon-Games/pot-community-servers#109]
We're currently trying to run our server (through gportal) but anything to do with the social tab causes the game to freeze for the user attempting to access the social tab or any sort of grouping.

This issue is not present on any other community server frequented by members. We make use of webhooks and CurveOverrides=...
Any hints?

**Comment by AlderonEmu** [comment]
Please check that this bug is still occurring for you in the current patch!
