### ISSUE TITLE
Feature Request - Command Autocomplete

### ISSUE THREAD

**Issue by Javano** [Alderon-Games/pot-community-servers#11]
**Is your feature request related to a problem? Please describe.**
Usability problems, I suppose?

**Describe the solution you'd like**
Right now, commands can be a little frustrating to use on users with excruciatingly long or complex names. It would make command usability a ton easier if we could simply type a substring of the target's name, and the game would find the nearest matching user.

Ex: **xXxXxSn1P3rG0DxXxXx** could be targeted with a much simpler substring: "**/teleport sn1P3r**".

**Describe alternatives you've considered**
This system would certainly be the most ideal -- albeit, probably not the simplest. If it's not feasible, being able to teleport by user ID would be a suitable compromise.

**Comment by AlderonEmu** [comment]
This feature has been forwarded to the QA team for review and will be closed.
