### ISSUE TITLE
Allow frame locking at 5 frames for smartphones.

### ISSUE THREAD

**Issue by rodrigomacaubas** [Alderon-Games/pot-community-servers#111]
During the game it is common for some players to use the minimizer to reply to a message or change the room on discord.

Some games already allow you to reduce the frames so as not to crash the smartphone when doing a quick task and not make the smartphone too slow when minimizing the game.

Currently the limit is 25 frames, but if only 5 frames were allowed, it would greatly reduce the stress on the smartphone, allowing you to do a secondary task when necessary without having to close the game.

Thanks for reading.

**Comment by AlderonEmu** [comment]
This feature has been forwarded to the QA team for review and will be closed.
