### ISSUE TITLE
bServerHungerThirstInCaves is no longer working as intended AND hunger is regenerating passively in homecaves

### ISSUE THREAD

**Issue by Nxzli** [Alderon-Games/pot-community-servers#113]
The configuration setting `bServerHungerThirstInCaves=True` no longer allows hunger and thirst to deplete in homecaves.

When testing this, I also found that hunger seems to regenerate passively while in home caves. I'm including screenshots to demonstrate this:
Hunger at 9:20pm
![image](https://user-images.githubusercontent.com/84545932/224528365-148353e2-c927-4f73-b016-116df7b0bbb4.png)

Hunger at 9:25pm
![image](https://user-images.githubusercontent.com/84545932/224528387-0018dd6c-c361-47a7-b422-fc33aba8c23a.png)

**Comment by Absurdponcho** [comment]
added fix in 24810
