### ISSUE TITLE
Feature Request: Damage Logs Webhook and Group Logs Webhook

### ISSUE THREAD

**Issue by OHKServer** [Alderon-Games/pot-community-servers#114]
Can we perhaps get a dedicated Damage logs Webhook
as well as group logs? 

For servers with rules this would be a big help.

Also

Can we get a Get location Rcon Command so we can see where a player is at that moment.
Thanks.

Webhook Documentation:
https://github.com/Alderon-Games/pot-community-servers/wiki/Webhooks
https://github.com/Alderon-Games/pot-community-servers/wiki/Webhook-Server-Python

**Comment by daanhansen** [comment]
This, I would love to see this!

**Comment by AlderonEmu** [comment]
This feature has been forwarded to the QA team for review and will be closed.
