### ISSUE TITLE
Server dying after 2 hours [happened after the last CSV patch]

### ISSUE THREAD

**Issue by Mist237** [Alderon-Games/pot-community-servers#117]
We are having massive freezes in our server after an hour of smooth gameplay.. We took off all stat changes and put it back to official standards in every way and it still happened. We don't know the cause anymore, are community servers having issues or something?

![image](https://user-images.githubusercontent.com/122040536/229012285-ac1cfa35-3d9b-4c6b-9a5f-8873d2a01378.png)

This has been happening since the CSV additions to curve overrides

![image](https://user-images.githubusercontent.com/122040536/229012296-f9b4c0d0-cbe2-4635-a7f5-e4d602f74f56.png)

but we already tested getting rid of every curve overrides, all of them 
still happens

it's kicking our players repeatedly at some point
it always seems to get worse after an hour, only after an hour, its smooth as butter for an hour. I have been convinced its not the provider since it only began with the patch that allowed us to change curve overrides more. Our specs are above the needed specs of Official Servers, so our server is stronger, and never taxed on CPU, RAM or bandwidth. This never happened to this severity until the last patch.

Again, to emphasize on the curve overrides, we have tested and removed them completely, wiped out everything, and tried and it was the same. Its smooth until its been 60 minutes, and afterwards it starts to collapse in on itself with lag. The problem has become serious the past 3 days but existed precisely when the patch CSV changes dropped, only to get gradually worse till now it is even kicking me after 2 hours and we all get a red icon on the top right corner of our screen meaning no connection. I am not sure if we are the only ones with this issue of our server.

We dropped our restart time to every 2 hours. It used to be 3 hours.

**Comment by LoneAeto** [comment]
Are you using local or remote db?

**Comment by Mist237** [comment]
First server that has these problems sometimes is Local, our second server is remote and rarely ever has these problems.

**Comment by AlderonEmu** [comment]
Please check that this bug is still occurring for you in the current patch!
