### ISSUE TITLE
Feature Request - Ability to tab through previous console commands

### ISSUE THREAD

**Issue by Javano** [Alderon-Games/pot-community-servers#12]
**Is your feature request related to a problem? Please describe.**
Command usability?

**Describe the solution you'd like**
Outside of some clever copy/paste wizardry, repetitively using the same series of commands tends to involve a lot of typing. One common feature most console interfaces have to address this issue is being able to use the _Up_ and _Down arrow keys_ to tab through previously used commands. 

Ex: While focused on the console, hitting the _Up Arrow_ once will autofill the last-used command. Hitting it again will autofill the command before that, etc.. 

**Describe alternatives you've considered**
No real alternatives, outside of a heck of a lot of copy/pasting.

**Comment by AlderonEmu** [comment]
This feature has been forwarded to the QA team for review and will be closed.
