### ISSUE TITLE
Selecting a certain dino makes you quit the server

### ISSUE THREAD

**Issue by Precka** [Alderon-Games/pot-community-servers#123]
So this bug happened more than 1 time but I was able to record it at the 6th or so, basically on server community, i'm able to join and all that, but if I try to select a dino, and for some reason this happens with dinos that were in homecaves before the log out, the game just throw me out of the server with the "error session lost" which in reality it's not real since the server is still active when I try to rejoin.
Here is the link: https://youtu.be/29q5nkwotBA

**Comment by Precka** [comment]
Here is a better example: https://youtu.be/KgJwU9Yg9OQ

**Comment by AlderonEmu** [comment]
Please check that this bug is still occurring for you in the current patch!

**Comment by Precka** [comment]
I checked and from what i've seen i can say that the bug has been resolved, thank you so much!
