### ISSUE TITLE
Kicking a player through the admin panel or user panel does not show up in the logs

### ISSUE THREAD

**Issue by Nxzli** [Alderon-Games/pot-community-servers#129]
When an admin kicks a player using the little boot icon in the admin panel or the player menu, the log does not show which admin did the actual kick.

This leaves room for admins to abuse the kick function against players using the boot icon without server owners being able to tell which admin did the kick.

Here is a screenshot of the kick in the log, with no indicator on which admin did the kick. 
![image](https://github.com/Alderon-Games/pot-community-servers/assets/84545932/74bc9cc8-019e-41a6-97e7-c622799ed672)

**Comment by AlderonEmu** [comment]
This has been forwarded it to QA
