### ISSUE TITLE
Feature Request - Nametag / Admin Panel Shortcuts 

### ISSUE THREAD

**Issue by Chebe-LFAW** [Alderon-Games/pot-community-servers#13]
**Is your feature request related to a problem? Please describe.**
Easy Access to Nametags

**Describe the solution you'd like**
Turning on / off nametags can tend to take a little while due to having to open the admin panel and click the box for "Force Show Nametags", especially if trying to quickly catch someone in a rule break / beginning a rule break just to get their name for future sake (could also benefit quickly catching hackers if any make it through the battle eye)

Would make it simpler than going through the admin panel - or as an alternative to make the admin panel accessible by a button (ie. Ctrl + Del)

**Comment by AlderonWombat** [comment]
Closing as this is already a feature.
