### ISSUE TITLE
Bug Report - Spectator Bird

### ISSUE THREAD

**Issue by Chebe-LFAW** [Alderon-Games/pot-community-servers#15]
**What bug did you experience?**

When selecting a bird from the admin panel to be able to enter spectate without logging,

With no way to go back onto your original dinosaur without logging out, there is a glitch where when you select the same dinosaur you went into spectate on, _(ie, i was on my cerato when i turned into a crow from my admin panel, when i logged out and selected my cerato, i could no longer do the animations / actions)_ where you can no longer do attacks / actions without quitting out of the game and back in to fix the issue

**Comment by AlderonWombat** [comment]
Closing as this is already a feature.
