### ISSUE TITLE
Feature Request - Server Config Multiplier for Water Quality

### ISSUE THREAD

**Issue by Decollates** [Alderon-Games/pot-community-servers#16]
So we have the bool for `bServerWaterQualitySystem=true` - Enables or disables the water quality system. 

Would it be possible to include a multiplier like `WaterQuantityMultiplier=5` in order to make sources of water have x5 the drinkable yield before the water is undrinkable?

**Comment by AlderonWombat** [comment]
Closing as this is already a feature.
