### ISSUE TITLE
Feature Request - Timers

### ISSUE THREAD

**Issue by Chebe-LFAW** [Alderon-Games/pot-community-servers#17]
**Is your feature request related to a problem? Please describe.**
No-- just a feature 
**Describe the solution you'd like**

Be able to add timers to dinos, like a cool-down, to possibly assist in avoiding people spam logging into a dino after dying and abusing the fact there is no timer

**Describe alternatives you've considered**
- Timer on "dead" dino (not delete it) 
- Possibly a timer on carnivores, after playing a herbivore
- not a super long timer, maybe 1-2 mins

**Comment by AlderonWombat** [comment]
Closing as this is already a feature.
