### ISSUE TITLE
Feature Request - Explicit Daily Restart Time

### ISSUE THREAD

**Issue by Javano** [Alderon-Games/pot-community-servers#19]
**Issue:** 
As far as I can tell, the only way to automate restarts is through the RestartLengthInSeconds config option, which is always relative to the server's last reboot time. But that can be sporadic, depending on when the server was last updated/rebooted; resulting in an unpredictable restart schedule for players, as well as the server attempting to reboot during inoptimal times. 

**Request:**
It would be ideal for us to be able to configure an absolute server reboot time offset, in addition to the RestartLengthInSeconds interval value, so the restart attempts are always at the same time each day regardless of when the server was last restarted.

**Example:**
RestartTime=1200 _(Noon)_
RestartLengthInSeconds= 43200 _(12 hour interval)_

_This would cause the server to restart at 12AM and 12PM, every day._

**Comment by AlderonEmu** [comment]
This feature has been forwarded to the QA team for review and will be closed.
