### ISSUE TITLE
PoT Teleporting Commands and Spectate

### ISSUE THREAD

**Issue by Jekyde412** [Alderon-Games/pot-community-servers#2]
The teleport commands seem to be a little confusing to some folk. Is there a possibility of them becoming more user friendly and a little more familiar? such as:

/goto (coordinates)
/goto (POIname)
/goto (user)

/teleport (user) (coordinates)
/teleport (user) (POIname)

/teleportall (POIname)
/teleportall (coordinates)
/teleportall (user)

/bring (user)

----------------

As for spectate; I believe having it available while in game, rather than logging out and selecting it, would be optimal for admins. This allows us to pop into bird form and dart over to a possible altercation without putting our own dino in the way if there is a fight going on, or risk it being killed by someone that's not being entirely honest about having trouble. IE: "Admin I'm stuck" only to get there and get nommed.

**Comment by Paleocolour** [comment]
This has been implemented
