### ISSUE TITLE
Creator Mode issue with undeletable objects (plus possible crash)

### ISSUE THREAD

**Issue by Javano** [Alderon-Games/pot-community-servers#21]
**Description:**
There's a bit of a UI hitch when working with undeletable objects.

If your selection includes a combination of deletable and undeletable objects (ex: a waystone), and the "Delete All" button is pressed, the properties panel will not update and will be showing properties for one of the deleted objects. 

While in this state, I can also reproduce consistent client crashes after waiting ~20-30s and playing with the Apply/Apply To All buttons.

**Steps To Reproduce:**
1. Enter creator mode
2. Select an array of objects, must include at least one deletable and one undeletable object.
3. Open the Selection dialog
4. Select a deletable object.
5. Click "Delete All".
6. The deletable objects will be removed, but the properties panel's state will not be updated.

**Clip:**

https://user-images.githubusercontent.com/6813253/132332192-2d687015-bac5-4362-959a-47e502642386.mp4

**Comment by AlderonWombat** [comment]
Closing as this is already a feature.
