### ISSUE TITLE
Editing water source "Water Volume" var doesn't save

### ISSUE THREAD

**Issue by Javano** [Alderon-Games/pot-community-servers#22]
**Description:**
While in creator mode, trying to edit the capacity of either natural water sources, or the water creator object doesn't ever appear to save.

**Steps To Reproduce:**
1. Enter creator mode
2. Select either a natural body of water or a placed water creator object.
3. Try to make a change to the "Water Volume" value.
4. Reselect that object and the water volume will not have changed.

**Clip:**

https://user-images.githubusercontent.com/6813253/132336719-87121140-e952-464c-9683-48276c9060fa.mp4

**Comment by AlderonEmu** [comment]
This bug has been forwarded to the QA team for review and will be closed.
