### ISSUE TITLE
Able to set objects past max FoodValue

### ISSUE THREAD

**Issue by Javano** [Alderon-Games/pot-community-servers#23]
**Description:**

Through the use of Creator Mode's "Apply to All" button, you can overset some objects past their maximum FoodValue.

**Steps to Reproduce:**
1. Enter Creator Mode.
2. Spawn two different objects of the same type, but different food capacities. (I used Berry Bush Cluster and Salt Rocks)
3. Select both objects.
4. Enter the Selection dialog and select the object with the greater capacity.
5. Set the value to something large and click "Apply to All".
6. The food value will be applied to both objects, even if it's past the maximum valid value for the smaller object. (The Salt Rocks' max value is 100, but I was able to set it to 500)

**Clip:**

https://user-images.githubusercontent.com/6813253/132338771-cfa272ce-8087-484f-ae55-5b4389f4529e.mp4

**Comment by KensonPlayz** [comment]
To be honest, I would actually like to be able to set the value higher. I have a chill server, so having less food sources with more food value would be very helpful.

**Comment by AlderonWombat** [comment]
Closing as this is already a feature.
