### ISSUE TITLE
Suggestions regarding RCON, Webhooks and Commands

### ISSUE THREAD

**Issue by daanhansen** [Alderon-Games/pot-community-servers#25]
**Suggestions Regarding RCON and webhooks:**

PlayerRespawn Webhooks:

- Perhaps it is possible to disable this one from triggering when administrators or people with the spectator permission as the AdminSpectate webhook already exists.

- Adding some more parameters to this webhook for us to play with would open up a huge amount of possibilities, as of now what we have is the following; PlayerName, AlderonId and Location. Having things such as DinosaurType or DinosaurCharacterName and maybe even growth would add a lot of value for us, as we can use these kind of things to set up automated events etc.

PlayerKiller Webhooks:

- With the addition of growth having both growth values of the killer and victim visible will allow for more creativity, including character name to identify the specific character killed, and that killed.

Suggestions for new webhooks:

1. An ItemBought webhook: for when a user buys an item such as an ability or skin. this could look as following:
```
ItemBought
{
PlayerName:"Daan",
AlderonId:"123-456-789",
CharacterName:"SwiftSnort",
ItemBought:"Claw Attack",
MarksSpent:500
}
```

2. A webhook for rcon requests for GetAttr which could look like the following:
```
AttributeRequest
{
PlayerName:"Daan",
AlderonId:"123-456-789",
CharacterName:"SwiftSnort",
AttrRequested:"movementspeedmultiplier",
AttrValue:1.35
}
```

For commands, so far I have one suggestion and that is perhaps a way to just add or remove marks, instead of setting a set amount.

I hope you guys find my suggestions valuable and I look forward towards what you guys have in store for the feature!
Feel free to contact me if you have any questions about anything on Daan#6592

**Comment by AlderonEmu** [comment]
This feature has been forwarded to the QA team for review and will be closed.
