### ISSUE TITLE
Info on where to place MOTD

### ISSUE THREAD

**Issue by litokey** [Alderon-Games/pot-community-servers#29]
Wiki does not advise where to place Rules.txt/Motd

The correct location is ( PathOfTitans/Saved ).  

Planning to add to the wiki.

...
Message of the Day

**Comment by deathlyrage** [comment]
Can you confirm where the motd.txt is supposed to go, we have tried the root (where the engine/pathoftitans folders/exe are, we have tried in the pathoftitans folder and we have tried where the game.ini/gameusersettings.ini files are and the server just keeps saying that it does not have an motd

Saved/MOTD.txt
Saved/Rules.txt

we will update the wiki

**Comment by Paleocolour** [comment]
Updated wiki pages.
https://github.com/Alderon-Games/pot-community-servers/wiki/Setting-up-Rules
https://github.com/Alderon-Games/pot-community-servers/wiki/Setting-up-Message-of-the-Day-(MOTD)
