### ISSUE TITLE
IP defined on Multihome not assigned to RCON port

### ISSUE THREAD

**Issue by defused** [Alderon-Games/pot-community-servers#31]
RCON port does not listen on defined IP, this can be a problem on multi-IP/multi-Server environments, as 2 servers with the same RCON port but different IP's will listen on the same RCON PORT.

https://gyazo.com/575e3f3f891f959cae1f27e8d9488a88

**Comment by deathlyrage** [comment]
Thanks for the report we will work on a patch for this.

**Comment by deathlyrage** [comment]
fixed in server side hotfix 10
