### ISSUE TITLE
Loaded mods don't work on second server join after leaving

### ISSUE THREAD

**Issue by deathlyrage** [Alderon-Games/pot-community-servers#32]
Possibly have a bug, when you join a modded server then leave, then try to connect to that server again it says something like the server is running mods you do not have (despite obviously having just been connected to it)

![image](https://user-images.githubusercontent.com/3461558/146967007-b3535e9c-30ad-44fc-b146-84ea1bca3998.png)

**Comment by Paleocolour** [comment]
Confirming that this is the case Rev 16542

**Comment by AlderonWombat** [comment]
Closing as this is already a feature.
