### ISSUE TITLE
Species Specific Group Limits and Death Penalty

### ISSUE THREAD

**Issue by LethalGiggles** [Alderon-Games/pot-community-servers#33]
**Group Limits**
The Max Group Limit is easy enough to set, however I'm having a difficult time setting up specific species group limits and where to find and place that specific INI.

**Death Penalty**
My server currently has passive growth enabled, however some of my testers noticed that when they die, they do not lose any growth. I currently do not see any specific server setting related to this.

**Comment by deathlyrage** [comment]
Re Group limits we can look into this.

Re Death Penalty, as far as i know if you die you won't loose growth past growth stages unless the option is set, this is covered on the wiki.

**Comment by LethalGiggles** [comment]
Thank you for responding so promptly! I looked through the wiki but didn’t
find an option to set the growth loss. Is there a specific title for it?

**Comment by LethalGiggles** [comment]
bServerHatchlingCaves=true 
bServerGrowth=true 
GlobalPassiveGrowthPerMinute=0 
QuestGrowthMultiplier=1 

These 4 settings were the only ones that mentioned growth.

**Comment by deathlyrage** [comment]
There is an additional server option that allows players to loose growth past their last growth stage / checkpoint when they die, currently by default players can't die and loose growth past their previous stage, if you are intending to run a more difficult server, you can enable this server option.
Game.ini
```
[/Script/PathOfTitans.IGameSession]
bLoseGrowthPastGrowthStages=true
```

**Comment by deathlyrage** [comment]
@Paleocolour can you check and make sure this is setup on the wiki and we didn't miss it.

**Comment by LethalGiggles** [comment]
Can the bLoseGrowthPastGrowthStages setting be further customized to show how much you lose growth?

Example) If you die to starvation you lose half a bar of growth but if you die to another player you lose one bar of growth

**Comment by AlderonWombat** [comment]
Closing as this is already a feature.
