### ISSUE TITLE
Idea: Spectator mode "Highlight Bodies"

### ISSUE THREAD

**Issue by Hotshotraptor** [Alderon-Games/pot-community-servers#34]
Allows Spectator mode the option to Highlight dead bodies.
- Could be through a command "highlightbodies"
- Or Could be done through the admin panel / a hot key (much like how you can see nametags with a hotkey or through the admin panel)

Essentially it would allow a spectator to highlight bodies with an outline which would show through foliage and terrain. (this would be in a specific radius).
- Would help massively for servers with body down rules.

**Comment by AlderonEmu** [comment]
Closing as this has been made a feature.
