### ISSUE TITLE
Idea: Expanding/branching out the AllowSpecatorAccess= - regarding the nametag feature

### ISSUE THREAD

**Issue by EZClappa** [Alderon-Games/pot-community-servers#35]
Currently I believe the use of the nametag feature is tied to AllowSpecatorAccess=True.

My wish and suggestion would be a possibility to split this up a little, with some of the reasoning being further customizability of admin tiers, bringing in newer/less trusted admins with less access and minimizing abuse cases and whatnot. 

Example below:
AllowSpecatorAccess=True/False
AllowNameTagsInSpectator=True/False
AllowNameTags=True/False 

A line for disallowing use of nametags in spectator is perhaps redundant, but the option to restrict nametag-use when you're a live dino in-game would definitely be of use to us.

**Comment by KensonPlayz** [comment]
This would be nice to give Streamers/Creators on your server access to Spectator but not nametags/etc.

**Comment by AlderonEmu** [comment]
This feature has been forwarded to the QA team for review and will be closed.
