### ISSUE TITLE
Idea: option for static weather and day time in the game.ini

### ISSUE THREAD

**Issue by BotanicTM** [Alderon-Games/pot-community-servers#37]
till yet i have not found: 
How can i set the weather and the daytime static?
i.e. daytime = 10pm and weather = ClearSky in the game.ini

would be nice for server events...

**Comment by KensonPlayz** [comment]
I agree. This would make it easier to run events like hide and seek or something. Keep it night and foggy for the entire event.

**Comment by AlderonEmu** [comment]
This feature has been forwarded to the QA team for review and will be closed.
