### ISSUE TITLE
Feature Request: Creator Items "Saves"

### ISSUE THREAD

**Issue by KensonPlayz** [Alderon-Games/pot-community-servers#38]
**Is your feature request related to a problem? Please describe.**
The feature request is a Quality-of-Life solution.

**Describe the solution you'd like**
Being able to save even just 2 or 3 'saves' or 'profiles' of creator mode placements would be super nice, so that way if you have a specific one for general gameplay, and one for events, you can easily switch between them. This in combination with persistent creator items between reboots would be super nice.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A.

**Comment by AlderonWombat** [comment]
Closing as this is already a feature.
