### ISSUE TITLE
Feature Request: Unstuck Feature

### ISSUE THREAD

**Issue by KensonPlayz** [Alderon-Games/pot-community-servers#39]
**Is your feature request related to a problem? Please describe.**
The feature request is a Quality-of-Life solution.

**Describe the solution you'd like**
On PC and mobile, it would be nice to have an way to get unstuck. I got stuck swimming in the tutorial cave as a modded giga and could NOT get out no matter where I went.

**Describe alternatives you've considered**
N/A

**Additional context**
Sometimes you can still get stuck in areas, and being able to get unstuck with a nearby TP to a safe spot would be very helpful. Make sure you can't trigger while in combat for people to avoid combat avoidance.

**Comment by Paleocolour** [comment]
We currently have the /respawn command that will respawn the player.
