### ISSUE TITLE
Feature Request - Additional Player Information While in Spectator Mode

### ISSUE THREAD

**Issue by Decollates** [Alderon-Games/pot-community-servers#4]
**Is your feature request related to a problem? Please describe.**
The feature request is a Quality-of-Life solution.

**Describe the solution you'd like**
While in spectator mode, can we have a togglable filter to show under the nametag placard the following information: species, sex, age. 

In addition, on the side panel while in spectator, can there be an space to accommodate AGIDs beside or next to player names? And, if possible, any time an AGID is clicked, it is copied to the clipboard?

**Describe alternatives you've considered**
The only other alternatives I've considered are committing to the legwork of travelling to these sorts of players to verify the information ourselves. However, it can be time-consuming to do so. 

For the second request, we can easily go to the player list and look up the AGID that way, but it can be a bit of a hassle to jump back between the two tabs just to cross-reference some data. 

**Additional context**
N/A.

**Comment by KensonPlayz** [comment]
This would be helpful for running 1v1 events. See someone's growth, grow them for the fight they're participating in, then reset their growth back to what it was before.
