### ISSUE TITLE
Feature Request: Favorite Servers

### ISSUE THREAD

**Issue by KensonPlayz** [Alderon-Games/pot-community-servers#40]
**Is your feature request related to a problem? Please describe.**
The feature request is a Quality-of-Life solution.

**Describe the solution you'd like**
Being able to favorite servers so they always show at the top would be super nice for community servers you play on all the time. Please consider adding this? I have 2 servers I'd be playing on all the time, with linked dinos.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by AlderonEmu** [comment]
This feature has been forwarded to the QA team for review and will be closed.
