### ISSUE TITLE
Idea: Add a command to admins "Grow"

### ISSUE THREAD

**Issue by wertrop** [Alderon-Games/pot-community-servers#42]
I consider it necessary to add the "Grow" command to administrators so that administrators can give growth to players, for example, measuring it in units from 0 to 1. This is necessary in order to return dinosaurs to people due to unforeseen circumstances, for example, when the player's growth flies off by itself, and it hurts him...

Now many people are saying: so that the team of adding growth to players from the server administration would be useful.

**Comment by EZClappa** [comment]
/setattr username growth 0-1 

This already exists.

**Comment by AlderonWombat** [comment]
Closing as this is already a feature.
