### ISSUE TITLE
Variables that do not have written definitions in the Wiki

### ISSUE THREAD

**Issue by litokey** [Alderon-Games/pot-community-servers#43]
[7:15 AM] Oida: will those be added to the server wiki? 

bLoseGrowthPastGrowthStages=true
CombatDeathMarksPenaltyPercent=25
CombatDeathGrowthPenaltyPercent=10
FallDeathMarksPenaltyPercent=5
FallDeathGrowthPenaltyPercent=2
SurvivalDeathMarksPenaltyPercent=10
SurvivalDeathGrowthPenaltyPercent=5

i'm sure a lot people would need them. Or i am just too blind to find it in the wiki xD

**Comment by Paleocolour** [comment]
These have been added, thank you!
