### ISSUE TITLE
Suggestion: Improvements to changing stats

### ISSUE THREAD

**Issue by OoWolfenDenoO** [Alderon-Games/pot-community-servers#45]
As of now, you can only change stats by typing out things in configuration files. If there was a place to see the default dino stats as a reference, that would really help. Something you could copy and paste and then change the numbers of.

The main part of this suggestion is to have a much better way of tweaking server settings, specifically for stats. An in game way for the server owner to change stats. In an Admin Panel there could be a tab for this.
 -There should be separate settings for the growth cave and growth earned outside of it, so you can gain normal rates of growth while doing the tutorial but can earn boosted growth once you're out.

![PoT server settings idea](https://user-images.githubusercontent.com/54220363/147593370-4fcfc5c7-2c39-4154-b425-dea2d193c2dd.jpg)
.

**Comment by menix1337** [comment]
Just a minor thought i had when reading this.

Quite often stats are stored in a cache or something, meaning that if you restart the server the changes you do most likely is lost.
A way to prevent this, could be (if this ever gets added) - save the edited information to a seperate .ini file - that gets read on server start ups (to save data changes).

This way the server hoster also can just reset defaults by removing data from this seperate .ini file.

**Comment by OoWolfenDenoO** [comment]
Idk if it would be possible for in game server settings (not while actually in the server tho) but at least a document with the default stats would be great so there's a reference point. Plus more options

**Comment by Zarkovka** [comment]
That is, now the stats are nowhere to be found?

**Comment by Paleocolour** [comment]
This is not planned, as this level of customization should be done through a game mod.
