### ISSUE TITLE
Suggestion: More server settings (For quests/groupquests, food, water, regeneration, etc)

### ISSUE THREAD

**Issue by OoWolfenDenoO** [Alderon-Games/pot-community-servers#46]
There should be settings you can change for specific quests, like how many marks they give you. So owners can change specific quests instead of having to change a multiplier that effects every quest. Foods should have settings such as value and regeneration rates. Same goes for specific bodies of water instead of one overall multiplier that changes all of them. There should be a reference sheet and map so owners know what exactly they're changing.

**Comment by AlderonEmu** [comment]
Please forward feedback or suggestions to the Feedback Board: https://feedback.pathoftitans.com/
