### ISSUE TITLE
Move Game Bans out from Game.ini, Global Bans & Extend Ban Information, Ban Timers

### ISSUE THREAD

**Issue by menix1337** [Alderon-Games/pot-community-servers#47]
**Suggestion 1: Move Game Bans out from Game.ini**

Currently all gamebans are stored in the Game.ini - however, this can cause a huge mess down the road as many servers will have thousands of bans in the long run.

This will lead into the worlds longest game.ini file, combined with it being hideous to go in to change settings, and have to scroll through thousands of bans.

Also the fear if Game.ini corrupts (due to players doing mistakes) - it will / can potentially erase the entire banlist.

**Solution**
Move bans out from Game.ini - potentially to GameBans.ini

____________________________________________________________________________________________

**Suggestion 2: Global Bans**

Just like you can share Dinosaur Files between servers, it could be nice with a setting in the Game.ini file - describing where your "GameBans.ini" should be on the machine. (Local, Remote, RemoteFile)

**If Local** = per server obviously, just uses the GameBan.ini in the config folder
**If Remote** = Like the Dinosaurs, they share on all servers using the same alderon / token info
**If RemoteFile** = We are able to specificly set the file in any folder on the PC (Ea: C:\PoTBans\GameBans.ini)
-- And through this all servers would have the same ban information, without having go onto 10 different servers, for 1 ban; or have to make bots do the job (as we have on Asura)

This means the possibility for servers to link them up together... Because lets say, we have 2 Normal servers & 1 Deathmatch server.
On Asura we would do our bans differently if the servers were Normal or Deathmatch..

____________________________________________________________________________________________

**Suggestion 3: Extended Ban Information**

Currently the bans in Game.ini (Or GameBans.ini; if you'd take this suggestion) doesn't save the reason of their ban.
When you ban a user you can type in a reason with "/Ban MENIX Toxic"
-- However upon joining it just says "BANNED"; the reason only shows if user was online during the ban.

Examples below:
Here i ban myself while being online
![image](https://user-images.githubusercontent.com/17611705/147628993-7459b17d-5ef7-4605-9143-3e3046833f42.png)

Here i try to rejoin the server
![image](https://user-images.githubusercontent.com/17611705/147628975-711d2218-110f-4c3b-a5f3-603a3709269d.png)

**Adding information such as a ban reason for the user would be nice; so it just doesn't say banned for them**
- obviously also if Suggestion 4 ever gets implemented (Ban Timers), having a ban countdown would be nice (Ea. 2 hours remaining)

____________________________________________________________________________________________

**Suggestion 4: Ban Timers**

Currently you are forced to either Permaban - or no ban.
It would be nice to see a return of Ban timers with such as:

/ban MENIX 2 Noob (2 hours) for reason: noob
/ban MENIX 0 Noob (Permaban) for reason: noob

Some servers want's to be able to punish users for XX hours, for infractions leading them into an automated unban.
Again, without having to use bots doing the job for them.

**Comment by Paleocolour** [comment]
I believe this is now all addressed
