### ISSUE TITLE
Bug: Nut Foraging-groupquest @ Redwood Basin

### ISSUE THREAD

**Issue by EZClappa** [Alderon-Games/pot-community-servers#48]
The group based quest "Nut Foraging" @ Redwood Basin is just simply bugged. 

It does not give % contribution when gathers either resource, and does not give any completion bonuses. It does give 1 mark per item collected. We're running this on a server without mods. 

TLDR Current behavior: No completion reward or visual %-contribution on Nut Foraging @ Redwood Basin-quests.
------ Expected Behavior: Regular quest contribution and rewards.

Not sure what pictures can improve this, since it's nothing more you need to do than get the quest, and there it is.

**Comment by deathlyrage** [comment]
I would recommend moving the report here https://github.com/Alderon-Games/pathoftitans-bugs/issues and providing more information and or a video.
