### ISSUE TITLE
Juvie body after killing adult

### ISSUE THREAD

**Issue by t-sex** [Alderon-Games/pot-community-servers#49]
If u have 75 lose of growth  (75 mean that from adult u became juvie) after killing adult u get juvie body. But sometimes u can get adult body but in most cases u still will get  juvie body
This is evidence https://youtu.be/aaJP5zYgy_w
Game Version: 0.0.0.16542

Operating System & Version: win 10

Alderon Games ID: 328-804-527

**Comment by AlderonEmu** [comment]
Please direct concerns regarding gameplay bugs to our public github https://github.com/Alderon-Games/pathoftitans-bugs/issues
