### ISSUE TITLE
Feature Request - Logging for Spectator Mode and Nametag Usage

### ISSUE THREAD

**Issue by Decollates** [Alderon-Games/pot-community-servers#5]
**Is your feature request related to a problem? Please describe.**
The best measure for servers to regulate and control their admins is through sufficient logging that can monitor their behavior and ensure that admin privileges are not being abused in order to gain an unfair advantage over others. 

**Describe the solution you'd like**
In addition to the current logging system in place, it would be great to have logs for the following events:
Admin entering spectator mode,
Admin leaving spectator mode,
Admin toggling nametags within spectator mode,
Admin toggling nametags within player/gameplay mode. 

If kill/death logs are developed, I'd like to see the following information included such as in the following scenarios: 
"Player A Killed by Admin"
Admin Nametags On: True

"Admin Death - Falling"
Admin Nametags On: False

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by AlderonWombat** [comment]
Closing as this is already a feature.
