### ISSUE TITLE
--auth-token vs -AuthToken=

### ISSUE THREAD

**Issue by litokey** [Alderon-Games/pot-community-servers#50]
Please take note that the cmd line arg is different from AlderonGamesCmd to PathOfTitansServer.

Industry naming conventions `--auth-token` vs `-AuthToken=` :

`--auth-token` is for the AlderonGamesCmd variable
`--auth-token` mytokenhere

`-AuthToken=` is for the PathOfTitansServer variable
`-AuthToken=mytokenhere`

AlderonGamesCmd has been updated to add a new command line argument:
`--auth-token` which can be used to provide the auth token.

AlderonGamesCmd will now also use the environment variable `AG_AUTH_TOKEN` just like PathOfTitansServer .
You will need to download the new update tool to take advantage of these changes as it doesn't self update yet.
This will mean you can completely remove all use of `-username` and `-password` in both AlderonGamesCmd and PathOfTitansServer .

**Comment by gilesknap** [comment]
@litokey I can't get my linux server to accept the auth token. I've regenerated the token a few times from two different accounts and always get:
```
Failed to Authenticate. Please make sure you are using valid authentication token or username / password that owns the game.
```

I've tried user/password just setting the `AG_AUTH_TOKEN` variable, passing the auth token with `--auth-token` but all attempts get the same error. 

Any ideas what I'm doing wrong? Thanks!
```bash
#!/bin/bash
THIS_FOLDER=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

export AG_AUTH_TOKEN=eyJ0eXAiOiJKV-REDACTED-awGbj_Y
export INSTALL_DIR=/AlderonServer
export SERVER_GUID="f59c377c-REDACTED-b3cf04f0"
export BETA_BRANCH="production"
export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1

while true; do
    echo restarting server at $(date)
    (
    set -x
    ${THIS_FOLDER}/AlderonGamesCmd-Linux-x64 --server true --beta-branch $BETA_BRANCH --auth-token $AG_AUTH_TOKEN --install-dir $INSTALL_DIR
    )
    break # remove this line to restart the server on crash
    echo restarting server ...
done
```
