### ISSUE TITLE
Much wanted RCON Command ideas from server hosters

### ISSUE THREAD

**Issue by menix1337** [Alderon-Games/pot-community-servers#54]
## Reasoning
From a server hoster / admin perspective it could be cool with the following commands working through Source RCON. These commands will make us be able to do remote management in a much more efficient way; without disrupting the other playing users.

## Message
`Message 123-456-789 Hello there`
`Message MENIX Hello there`

> Sends a `Message` from RCON Client to a `specific target` ingame. This Message would appear in all of the chats (Not announcement box), not depending on chat tab what the user is in - they will see it in all of their chat tabs.

`Message Hello there`

> Sends a `Message` to `all users` ingame's chatboxes (Not announcement box), not depending on chat tab what the user is in - they will see it in all of their chat tabs.

## Announce (Target)

Currently admins ingame have the oppertunity in admin panel to announce to a specific player - this would be lovely to have through RCON too. 

Through RCON it is already possible to announce to the entire server with `Announce HELLO` - but an alternative oppertunity to do it to a specific player only could be awesome

`Announce 123-456-789 Hello and Welcome to Asura`
`Announce MENIX Hello and Welcome to Asura`
> Announces to a specific user from Alderon ID, in the their announce box in the middle of their screen.

**Comment by AlderonEmu** [comment]
This feature has been forwarded to the QA team for review and will be closed.
