### ISSUE TITLE
Death Penalty Bug

### ISSUE THREAD

**Issue by devildinosaur** [Alderon-Games/pot-community-servers#55]
### **Description:** 
<hr>

When a player get killed, the size of corpse of his dino is reduced to the size (growth) that the player will have after rebirth based on the death penalties.
- In fact, this eliminates the possibility of setting hard death penalties, because there would be no corpse for a killer or it would be too small.
- This can be compensated for by an increase in the amount of food in the corpse in proportion to the penalty, but the corpse will still be visually abnormal.

### **Video/Screenshot:**
<hr>

> [YouTube](https://youtu.be/hQsvR9LDRho)

### **Add. info:**

- Game Version: 0.0.0.16542
- Alderon Games Username: AoDadmin
- Alderon Games ID: 250-536-862

**Comment by AlderonEmu** [comment]
Please direct concerns regarding gameplay bugs to our public github https://github.com/Alderon-Games/pathoftitans-bugs/issues
