### ISSUE TITLE
Feature Request - Grouping Configs

### ISSUE THREAD

**Issue by Decollates** [Alderon-Games/pot-community-servers#6]
**Is your feature request related to a problem? Please describe.**
This option would probably be best-suited for servers that are attempting to employ a more realistic standard for gameplay. 

**Describe the solution you'd like**
Server configs to allow server owners to define which species an animal can or cannot group with, in order to reduce instances of mix-packing or overpacking. 

**Describe alternatives you've considered**
Currently grouping limits are defined by a size float that can be changed. While this is already appreciated, we hope that more can be done. 

**Additional context**
N/A

**Comment by Paleocolour** [comment]
I believe this is already implemented here: https://github.com/Alderon-Games/pot-community-servers/wiki/Server-Configuration-Options#igamemode-options
