### ISSUE TITLE
ServerDeadBodyTime config does not seem to be working.

### ISSUE THREAD

**Issue by Nxzli** [Alderon-Games/pot-community-servers#60]
It would appear that the ServerDeadBodyTime configuration setting does not work. When setting a value, there is no change in the decay time of bodies at all. I have tried the following with no results:

ServerDeadBodyTime=0
ServerDeadBodyTime=1800
ServerDeadBodyTime=0.025 

It is currently in my server config as this:
```
[/Script/PathOfTitans.IGameSession]
ServerDeadBodyTime=0
```
I have also tried setting it under the header [/Script/PathOfTitans.IGameMode] just in case, but that also did not work.

**Comment by elamec** [comment]
This works fine for me:

[/Script/PathOfTitans.IGameSession]
...
ServerDeadBodyTime=3

You can check it here:
https://www.youtube.com/watch?v=h7YKLoCg-eY&t=11s

Probably it can take values from a particular range which is not listed on the wiki (0 might be invalid / means use default, and there seems to have an upper limit), but small integers seem to work fine.

+ Be careful when using this option, it seems to applied also for dropped fish!

**Comment by Nxzli** [comment]
Thank you for the insight!

Due to the nature of our server, we'll need the bodies to last a bit of time so carnivores have time to eat them and stick with them for a little while. I will try some smaller integers than 1800 and see if anything works.

**Comment by devildinosaur** [comment]
I have the same issue. Even '0' value does not make bodies to lay for an unlimited time.

**Comment by litokey** [comment]
This seems to still be an issue.

What is the correct scale?

**Comment by AlderonWombat** [comment]
Closing as this is already a feature.
