### ISSUE TITLE
Unable to rebind Show Admin Names command

### ISSUE THREAD

**Issue by Nxzli** [Alderon-Games/pot-community-servers#61]
Currently, the show admin names setting is set to N as default, but even when you rebind the key in the settings, it still uses N and not the new key.
Ex. I set my Show Admin Names to \, and when I hit \, nothing happens, but when I hit N, the nametags are enabled/disabled.
I've had the same result no matter the key that show admin names is bound to, it always uses N instead.

**Comment by AlderonWombat** [comment]
Closing as this is already a feature.
