### ISSUE TITLE
SourceQuery issue / Time out

### ISSUE THREAD

**Issue by TeutonicServers** [Alderon-Games/pot-community-servers#62]
Looks like SourceQuery has a problem with multiple servers on one machine as we can query always one server only at the same time.

Example: Our Classic server is working and showing up the players. If we try adding the second we are getting a time out.

If i close the classic server and start the second one, it takes some time and the second is working. And so on.

We tried setting up like the wiki with all variations like

Port:0
IP: 0.0.0.0

Also with adding port and IP/local IP and also with binding in the command lines. Nothing.

Still only be able to query one server at the time on the same machine.

**Comment by menix1337** [comment]
I just did a test on ours using the 'gamedig' package 
https://www.npmjs.com/package/gamedig

I did not experience the same result, and i was able to query 2 servers on same machine after eachother.

Using auto-decetion so its automatically Base port + 4 on my test

**I used the public-test-demo branch however**
Not sure if theres a Source Query difference in that from the demo one

![image](https://user-images.githubusercontent.com/17611705/149098989-73119bf8-1a9a-4865-8c48-a7cd7900d05c.png)
![image](https://user-images.githubusercontent.com/17611705/149099001-7fd6efcd-4381-4acb-8a07-512606c6bf56.png)

**Comment by TeutonicServers** [comment]
We will try it out later and give some feedback.

**Comment by TeutonicServers** [comment]
After trying out stuff it seems like Map Mods Are Breaking the query. As soon we are removing the map mod, it's possible to query the server. If we add it back, it's breaking.

Map mods -> Query time out.
Panjura -> Multiple Server working fine.

**Comment by Paleocolour** [comment]
This is not planned, as this level of customization should be done through a game mod.

**Comment by menix1337** [comment]
> After trying out stuff it seems like Map Mods Are Breaking the query. As soon we are removing the map mod, it's possible to query the server. If we add it back, it's breaking.
> 
> Map mods -> Query time out. Panjura -> Multiple Server working fine.

Seen more people mention this on the official Discord too.

**Comment by AlderonEmu** [comment]
Is this issue still occurring for you?
