### ISSUE TITLE
Custom Discord URLs containing non letter & numbers isn't accepted by the game.ini Discord=xxxx

### ISSUE THREAD

**Issue by menix1337** [Alderon-Games/pot-community-servers#65]
Discord URL in game.ini: dino-mite 
Discord URL browser: https://discord.gg/dino-mite

-- Recieves the following error.
`[2022.01.15-01.33.33:574][794]AlderonLog: Error: IAlderonCommon:RegisterServerCallback() Failed - {"data":{"success":false,"status":422,"message":"The given data was invalid.","error":"E_VALIDATION","code":1,"content":{"discord_invite_id":["The discord invite id may only contain letters and numbers."]}}}`

However the error is invalid, as vanity urls (discords own custom urls) can contain stuff such as `-` & not `only` letters and numbers; leading into some servers not being able to use the service to give them a Discord Icon in-game upon joining.

**Comment by ConnorVG** [comment]
This is fixed.
