### ISSUE TITLE
Glitchy playing with Xbox one controller 

### ISSUE THREAD

**Issue by Nightmoon84** [Alderon-Games/pot-community-servers#66]
I play pot on an iPhone 11 Pro with a new Xbox one controller I just bought. Most of the time when I move my Dino it glitches and makes my Dino spaz out. It mostly does this when I walk/run straight forward. My game is up to date as well so maybe it’s just an Xbox controller thing?

**Comment by Paleocolour** [comment]
Please report this on the game bugs github
