### ISSUE TITLE
Suggestion for documentation

### ISSUE THREAD

**Issue by linuxdude25** [Alderon-Games/pot-community-servers#69]
When you download the server files using the Update script, it does not automatically create certain files and folders, such as Game.ini and the rest of the "Saved" folder files.
Starting the server without any additional arguments will create these files in the appropriate place even if the server doesn't start properly.

I suggest adding this is a step or a note in https://github.com/Alderon-Games/pot-community-servers/wiki/Server-Configuration-Options

**Comment by Paleocolour** [comment]
added!
