### ISSUE TITLE
Feature Request - Spectator Invisibility and Camera Lock

### ISSUE THREAD

**Issue by Decollates** [Alderon-Games/pot-community-servers#7]
**Is your feature request related to a problem? Please describe.**
Not a problem or even a quality-of-life thing, just an additional feature. 

**Describe the solution you'd like**
The ability to toggle the bird avatar that is assumed every time an admin enters spectator mode *invisible*, with no shadow. 

In addition, being able to "lock on" to a player in spectator mode so that you can follow their position as they move through the map. ARK: Survival Evolved provides the best example of this. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by AlderonWombat** [comment]
Closing as this is already a feature.
