### ISSUE TITLE
Request: A global "reset attributes" command.

### ISSUE THREAD

**Issue by linuxdude25** [Alderon-Games/pot-community-servers#75]
While doing tests or tweaking attributes, it would be great if there was a command that would just reset all attributes to their defaults instead of using a sheet or remembering the defaults.
Ideally, it would reset everyone's attributes to their defaults.

**Comment by devildinosaur** [comment]
Save file does not include changed characteristics, so you can just relog.

**Comment by linuxdude25** [comment]
> Save file does not include changed characteristics, so you can just relog.

I'm aware of that but it would be great if we could just reset everything in game without leaving the session or if multiple people are changing attributes.

**Comment by AlderonEmu** [comment]
Please forward feedback or suggestions to the Feedback Board: https://feedback.pathoftitans.com/
