### ISSUE TITLE
Request: Logs showing damage dealt to characters

### ISSUE THREAD

**Issue by Nxzli** [Alderon-Games/pot-community-servers#76]
It would be incredibly helpful to be able to get a log of damage dealt to characters. It would make moderation and implementing combat rules a lot easier
Something like this:

[7:11:20 PM] Player1 [000-000-000] [Suchomimus 1] [Player] has hit Player2 [908-119-661] [Daspletosaurus 1] [Player] for 50 damage and 15 bleed.

**Comment by AlderonEmu** [comment]
This feature has been forwarded to the QA team for review and will be closed.
