### ISSUE TITLE
New stat: SwimmingStaminaConsumptionRate

### ISSUE THREAD

**Issue by Nxzli** [Alderon-Games/pot-community-servers#77]
I'm suggesting that there to be a stat that allows server owners to change how fast stamina drains while swimming for specific animals

**Comment by Paleocolour** [comment]
This is called `StaminaSwimgCostPerSecond` `StaminaFastSwimCostPerSecond` `StaminaDiveCostPerSecond` `StaminaFastDiveCostPerSecond`

**Comment by Tyranid0548** [comment]
Hey Paleo, Is the StaminaSwimgCostPerSecond supposed to have the g between Swim and Cost?

**Comment by Tyranid0548** [comment]
Yeah these don't seem to be adjustable stats for us currently. @Paleocolour

**Comment by AlderonEmu** [comment]
This has been forwarded to the QA team for review!

**Comment by AlderonEmu** [comment]
Closing as this issue is not a bug or will not be fixed.
