### ISSUE TITLE
bServerAllowMap doesn't work fully as intended

### ISSUE THREAD

**Issue by Nicosia89** [Alderon-Games/pot-community-servers#78]
Server Hoster: GPortal
Server OS: Windows Server
Server Slots: 50
Server Location: Frankfurt, Germany

expected behaviour:
By adding the option "**bServerAllowMap=false**" 
to the Config File **PathOfTitans\Saved\Config\WindowsServer\Game.ini** 
under **[/Script/PathOfTitans.IGameSession]**
it should behave as followed for users ingame on the Server: the full map (ingame standard Keybind: M) should nomore be accessible. Also, the minimap on the top left corner of the screen should no more be displayed.
In the official documentation for server options it says for bServerAllowMap: "Enables or disables the map and minimap for the entire server."

observed behaviour:
While the full map (standard keybind: M) ingame is disabled and no longer accessible, the minimap on the top left corner of the ingame screen is still visible.

Screenshots:
![grafik](https://user-images.githubusercontent.com/57940448/155847875-7c07f3b2-21a8-4e2b-929b-ade63ce395e3.png)
ingame screenshot while being connected to the server. Minimap in the top left corner is still visible, though bServerAllowMap is set to false.

![grafik](https://user-images.githubusercontent.com/57940448/155848178-1d91725b-b95f-43ae-8399-ad819ddbf5d2.png)
Screenshot of the configuration file in GPortals Administration Panel. See the Server Option on the end of the option List.

**Comment by elamec** [comment]
Hi,
It's only a documentation issue, the related config option is
bServerAllowMinimap=false
but it's missing from wiki and it's incorrectly stated as it'd be set by the bServerAllowMap entry.

**Comment by Nicosia89** [comment]
> Hi, It's only a documentation issue, the related config option is bServerAllowMinimap=false but it's missing from wiki and it's incorrectly stated as it'd be set by the bServerAllowMap entry.

Nice! Thank you very much!

**Comment by Paleocolour** [comment]
I have updated the documentation.
