### ISSUE TITLE
Unreal Engine 5 Causing Core Stat Changes to Crash Server.

### ISSUE THREAD

**Issue by Rasmen303** [Alderon-Games/pot-community-servers#79]
I was experimenting with code, adding changes to multiple dinosaur's code such as sarco and campto, giving sarco speed and campto health using CurveOverrides=(CurveName="Sarcosuchus.Core.MovementSpeedMultiplier",Values=(2.3,2.3,2.3,2.3,2.3)) and CurveOverrides=(CurveName="Camptosaurus.Core.MaxHealth",Values=(500,600,700,800,1000)). It was working just fine up until this new engine update. Every time I try to load up in my server with a changed code for a dino, it loads for a moment longer than usual, before it kicks me saying "The connection to the server has been timed out." It does not even let me get to the character select screen no matter what dinosaur's stats I change. I have tried multiple other stat changes and they all lead to the same result with me getting kicked from the server. Will there be an update to fix this? Perhaps the developers of path of titans changed their code slightly to suit Unreal Engine 5. Or if it is something I did wrong on my end, please let me know. I really wanted to make a server with the main roster's stats completely flipped around.

**Comment by AlderonEmu** [comment]
Unable to reproduce this in 26458, please check that this bug is still occurring for you in the current patch!
