### ISSUE TITLE
Feature Request - Spectator Camera Maneuverability

### ISSUE THREAD

**Issue by Jekyde412** [Alderon-Games/pot-community-servers#8]
**Is your feature request related to a problem? Please describe.**
Just a quality of life feature to make it easier to move around the map. 

**Describe the solution you'd like.**
If I remember correctly (if I'm wrong, please correct me), your spectate camera flew where ever you happened to point. IE: Toward the sky and you flew up. Toward the ground you flew down. Currently you have to use the Shift button and Ctrl respectively for elevation, and it's extremely slow. 

For better control of the camera, perhaps it could be reverted to what it was previously, where you would fly in the direction that your camera is pointed rather than relying on hitting Shift + Control + W in order to move down quickly. For someone with hand problems, that's extremely awkward and painful to do. 

Spectate also used to allow you to ghost through the map, though that seems to be gone as well. For a map that has extensive cave systems (such as Cerulean), being able to ghost through the walls in order to help someone would be perfect.

**Comment by AlderonEmu** [comment]
This feature has been forwarded to the QA team for review and will be closed.
