### ISSUE TITLE
Red X icon next to budget on creator mode

### ISSUE THREAD

**Issue by roryt894** [Alderon-Games/pot-community-servers#80]
Bug Explanation:
When in creator mode as a spectator, initially there is a red X next to the budget in creator mode, very misplaced so I am assuming not intentional, and it then disappears once an item has been placed. (image showing the issue will be attached below).
Unsure whether this X is meant to be intentional but given the awkward placement of it on the screen I am assuming it is a genuine bug.

When does the bug occur?:
Everytime entering creator mode for the first time in spectator mode. Leaving and re-entering it does not cause the X to reappear, only ever appears when entering the very first time you go into it from spectator mode.

[https://ibb.co/tmQ3qN2](url)
![Screenshot 2022-03-31 211427](https://user-images.githubusercontent.com/84544258/161143729-c997117a-1d0c-41a9-80d2-e74a5687bb68.png)

**Comment by AlderonEmu** [comment]
Closing as this has already been fixed in a more recent patch.
