### ISSUE TITLE
Group leaving bug (shows ID's and PC name and default alderon ID instead of playername)

### ISSUE THREAD

**Issue by roryt894** [Alderon-Games/pot-community-servers#81]
Explanation of the issue:
When a member leaves a group, occasionally there is an issue where the text is wrong. Where it should show the players name and Alderon ID, as it usually does when someone leaves a group, it instead shows the name of a desktop PC (DESKTOP-6E81CSR-D1F8), "Username" in place of the players username, a placeholder ID (123-456-789), and then Build ID and Mod ID as it would with a mod on the mods page.

When does the issue happen?:
When a player leaves a group. So far the issue has only been witnessed a handful of times, but the recurrence of it may suggest a bug rather than a client-side issue.
![Screenshot 2022-03-31 212146](https://user-images.githubusercontent.com/84544258/161143765-c467c7d1-a97b-4db8-bc0b-ffa4c27b56f2.png)

**Comment by AlderonEmu** [comment]
Please direct concerns regarding gameplay bugs to our public github https://github.com/Alderon-Games/pathoftitans-bugs/issues
