### ISSUE TITLE
Announce not accepting PlayerName as argument through chat command

### ISSUE THREAD

**Issue by linuxdude25** [Alderon-Games/pot-community-servers#85]
In the admin panel, you can send announcement messages to a specific person and only they see it.

But you can't do it through chat commands currently, instead of accepting the player's name as an argument, it adds it to the announcement and shows it to everyone on the server.

**Comment by menix1337** [comment]
#54 - A part of my wishlist in here as well; I see a dev assigned - as its not of important priority atm, I guess they come around to it once all the unreal engine 5 stuff is in the back! :D

**Comment by linuxdude25** [comment]
Duplicate of #54
