### ISSUE TITLE
QuestMarksMultiplier Server Setting bugged.

### ISSUE THREAD

**Issue by chillmawx** [Alderon-Games/pot-community-servers#86]
## Expected Behavior
The Quest reward for completion should be increased by the multiplier alongside the reward for picking up an item.

## Current Behavior
Quest completion reward is still the vanilla amount (i.e., at x3 multiplier, picking up an acorn for a "Gather Nuts..." quest gives 3 marks. However, completing the gather quest gives the same amount of marks as vanilla would.)

## Reproduction Steps

- Put the QuestMarksMultiplier setting into the game.ini under the [/Script/PathOfTitans.IGameSession] header.

- Start server.

- Log in and do a quest.

## Evidence (Screenshots & Videos)
https://drive.google.com/file/d/1iXZVZ8Mi001WmmXtcFijY9Rm_syVnLKQ/view?usp=sharing

## Crash Logs

(If Applicable. No logs needed if there is no crash.)

## Build Information

**Game Version:** 0.0.0.18638

**Operating System & Version:** Windows 10

**Alderon Games ID:** 069-808-901

**Comment by AlderonEmu** [comment]
Is this issue still occurring for you?

**Comment by chillmawx** [comment]
Why are you asking a year and a half later? I'm publisher banned from the
game and wouldn't piss on your devs to save them.

🙄

**Comment by chillmawx** [comment]
Do not email me again.
