### ISSUE TITLE
Request: Allow /demote and /promote to work on offline players

### ISSUE THREAD

**Issue by Nxzli** [Alderon-Games/pot-community-servers#87]
It would be very nice to be able to /promote and /demote players in player roles even when they are offline, that way the server does not need to be restarted for the change to take effect, and server admins are able to apply these roles even when the player is not online.

Currently when you try to use /promote or /demote on someone who is offline, you're met with an error message stating that they are not online, and it remains unchanged.

**Comment by xBocT-ncuTaku** [comment]
I agree, this also applies to commands: /addmarks, /removemarks.

**Comment by elamec** [comment]
For the same reason, promote can't be used reliable during login. When login webhook is called, in many cases user is still reported as 'not online' when trying to promote them. Enabling offline usage of promote would solve this issue too.

**Comment by AlderonEmu** [comment]
This feature has been forwarded to the QA team for review and will be closed.
