### ISSUE TITLE
Mod support for Linux clients and servers.

### ISSUE THREAD

**Issue by linuxdude25** [Alderon-Games/pot-community-servers#89]
It's been **10, almost 11 months** since mods came out and there is still not even an eta on Linux support.
Our community server runs on a dedicated Linux machine and the inability to add mods that our members have been requesting is starting to impact us. 
This also locks us out of all the modder created maps and with the latest patch removing or breaking the Mechanics Test Map, we are left with only one map option. #90 

Please add mod support for Linux.

**Comment by deathlyrage** [comment]
![image](https://user-images.githubusercontent.com/3461558/167290321-3dcf6592-07d4-421a-bc51-5a38b5339fae.png)

mods are now supported for Linux and Linux servers. Starting with grim expanse. Here is a example of it running on my steam deck. Keep in mind mod authors will have to ship mod updates with Linux checked.

**Comment by linuxdude25** [comment]
Amazing, great work!
