### ISSUE TITLE
Mechanics Test Map no longer loads

### ISSUE THREAD

**Issue by linuxdude25** [Alderon-Games/pot-community-servers#90]
As of the latest patch, the Mechanics Test Map is no longer loading as the server map. The game.ini line has not been changed.
![image](https://user-images.githubusercontent.com/98142667/165379378-ddc388ca-2ac1-4fbc-987d-caac6ab4764a.png)

These are the only lines in log relating to the Test Map

![unknown](https://user-images.githubusercontent.com/98142667/165381590-e825594d-895e-4020-9958-a5ff41b61de1.png)
![unknown](https://user-images.githubusercontent.com/98142667/165380863-1d32e36f-bb48-4233-9631-229f2683690c.png)

The first error line says to check the log for details but I was unable to find anything else in any logs in the server folder.

**Comment by DinosaurRaptor** [comment]
I agree, I really liked the Mechanics Test Map and was an easy deathmatch map and you can get right into action. Now we either need an admin to tp us or use a small modded map. The Mechanics Test Map was a basic gym or deathmatch map.

**Comment by AlderonWombat** [comment]
Closing as this is already a feature.
