### ISSUE TITLE
Suggestion: Allow server owners to raise or lower the amount of dinos a player can make

### ISSUE THREAD

**Issue by OoWolfenDenoO** [Alderon-Games/pot-community-servers#91]
I'm not sure if this is a thing already but if not, allow server owners to change the number of character slots a player is allowed. The default amount of dinosaurs a player can have on a server is 20. There are more than 20 dinos currently in game though and being unable to grow all of them kind of sucks.

**Comment by chillmawx** [comment]
Please do this; many of my players have run out of capacity and are attached to their roster but want to be nested in again or make a new character!

**Comment by AlderonEmu** [comment]
Closing as this is already a feature.
