### ISSUE TITLE
Community Server In-Game banning not working

### ISSUE THREAD

**Issue by Tyranid0548** [Alderon-Games/pot-community-servers#94]
I have attached a URL link to the clip video in question. I also tried banning from the admin panel as well but just clicking confirm didn't seem to do anything as the person remained on the server.

If it also helps I'm currently using Pingperfect as my host and the server name is Obsidian Jungle

[https://medal.tv/games/path-of-titans/clips/lZEUZR_ye1RbS/d13375pk8trB?invite=cr-MSxyUmMsNjU5ODYxMDcs](url)

**Comment by Tyranid0548** [comment]
So I can confirm the command /ban does work. But the banning from the Admin Panel and Social Tab do not work.

**Comment by AlderonWombat** [comment]
Closing as this has already been fixed in a more recent patch.
