### ISSUE TITLE
Spinosaurus BodyFoodAmount needs to be fixed

### ISSUE THREAD

**Issue by Tyranid0548** [Alderon-Games/pot-community-servers#95]
Currently the amount of food Adolescent and Sub Adults give is unchanged from the Juvi growth stage. Sub-Adult Spinosaurus's give same food as Juvi ones. Example below can be seen the issue.

Spinosaurus.Core.BodyFoodAmount",Values=(50,100,100,100,2000))

**Comment by AlderonEmu** [comment]
Closing as this has already been fixed in a prior patch.
