### ISSUE TITLE
ServerAdmins can't join server if whitelist is active

### ISSUE THREAD

**Issue by elamec** [Alderon-Games/pot-community-servers#96]
If the server has a whitelist (and there is at least one valid Alderon Id on it), ServerAdmins can't join to the server unless they're on the whitelist.

Additional info: any (other) user is able to join, when they (are not on the whitelist but) have any role assigned. (I mean any role which is set up in Commands.ini file.)
That is, a ServerAdmin can join to the server if whitelist is active (with any random Alderon Id(s) enabled except the particular ServerAdmin) if ServerAdmin has any additional role assigned, otherwise they can't. 

Reproduction:
(Some admins are configured in Game.ini file:
`ServerAdmins=099-337-896`
and make sure that this ServerAdmin has no other role assigned in Commands.ini file.)

Add some random Alderon Id to the whitelist, e.g.:
`// Alderon Id Whitelist for Path of Titans`
`// Format Information`
`// Alderon Id (required)`
`//(EXAMPLE) 525-053-709`
`111-111-111`

Observe that with this setup, ServerAdmins can't join to the server, server rejects their join request with 'Server restricted to whitelisted users only.' error message.

Remove the (fake) user from the whitelist (wait until whitelist reload is logged or reload it via rcon), now ServerAdmins are able to join.

**Comment by AlderonEmu** [comment]
This has been fixed in a future patch!
