### ISSUE TITLE
Possibility to disable the whole server quest system (Server)

### ISSUE THREAD

**Issue by TeutonicServers** [Alderon-Games/pot-community-servers#97]
Matt told me there should be a command like: bServerQuests to disable the quest system. Sadly not working. Would be great if you guys take a look at this, that we can disable ALL quests (whole quest system) in the config properly.

Or maybe its just the wrong setting? Let me know guys.

Thank you!

**Comment by AlderonEmu** [comment]
If you are still having this issue, please try the following:

`bServerLocalWorldQuests=False` 
`MaxGroupQuests=0`
`MaxCompleteQuestsInLocation=0`

For the time being, users will receive the first personal quests in the POI. Once those are completed, no other quests should show up. 

If this issue has already been resolved, we will go ahead and close this up!
