### ISSUE TITLE
Dinosaur saves disappearing with restarts

### ISSUE THREAD

**Issue by TarasaurusRex** [Alderon-Games/pot-community-servers#99]
Description: Upon restart (manual or automatic) the mods seems to be loading incorrectly, which disables various saves of our player's dinosaurs. Server 1 is a modded map, Cerulean Isles, and Server 2 is on Panjura. So far, server 2 has not had this issue, or if it has its happened rarely compared to server 1. Usually manually restarting the server via the dedicated server, not in-game commands seems to fix it, however, it can take 4+ manual restarts in order for the server to load the mods properly. This issue has persisted for the past couple months, with the most recent mod being the map mod being disabled and not the modded creatures, though they continue to be spotty. 
Both servers are identical, modded creatures, settings, and all except for server 1 being on Cerulean Isles map and server 2 being on Panjura map. 

How To Reproduce the Bug: Bug occurs randomly with automatic and manual restarts, at least half the time.

Video/Screenshot: N/A

Game Version:1.1.71(Launcher) 0.0.0.20333-Shipping
Alderon Games Username: TarasaurusRex
Alderon Games ID: 065-693-885

**Comment by TarasaurusRex** [comment]
As of the patch on 8-12-2022 the issue persists. The server has been restarted since the patch, however so far the map mod seems to be verifying correctly, there is still issues with modded creatures not loading properly.

**Comment by AlderonEmu** [comment]
Is this still occurring for you?

**Comment by TarasaurusRex** [comment]
no, we wiped our servers not too long after i made the bug report and that
fixed the issue.

**Comment by AlderonEmu** [comment]
Closing as this issue has been resolved.
